@host = http://192.168.88.205:8005
@gpio1 = 17
@gpio2 = 27

### setup gpio1
GET {{host}}/setup/{{gpio1}}/i 

### setup gpio2
GET {{host}}/setup/{{gpio2}}/i

### read1
GET {{host}}/read/{{gpio1}}

### read2
GET {{host}}/read/{{gpio2}}

### clean
GET {{host}}/clean
